In [1]:
import numpy as np

In [2]:
np.meshgrid?

In [12]:
a=[1,2,3]
b=[2,5,3]
c,d=np.meshgrid(a,b,indexing='ij')
e,f=np.meshgrid(a,b,indexing='xy')

In [14]:
print(c)
print(d)
print(e)
print(f)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[2 5 3]
 [2 5 3]
 [2 5 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[2 2 2]
 [5 5 5]
 [3 3 3]]
